<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link Beasiswa_link</name>
   <tag></tag>
   <elementGuidId>b22b99e9-8de5-4bd3-a23d-ce648cf905ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d117748c-0155-4d45-8eb2-c411315177a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>fe73d09f-5b59-4888-aaee-a82ee5ed3e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>198cbf3d-8be7-4e31-a166-315c00ff7b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1081243f-b203-4d30-892c-a1dbb44b72b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>00e014fc-234d-429b-922a-7bcb0098280d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>www.jayaabadi.com/beasiswa/1</value>
      <webElementGuid>b8720b29-e828-4276-95aa-82db01adde61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link&quot;)</value>
      <webElementGuid>d84c478e-1600-4273-9642-051459e74084</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='link']</value>
      <webElementGuid>fb9b9704-b128-478a-befe-41524544a15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[5]/input</value>
      <webElementGuid>814e1288-20e5-4f08-b5be-157ee3073f0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>43587079-4442-4287-9c66-94cde5853ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'link' and @type = 'text' and @id = 'link']</value>
      <webElementGuid>819d9856-d095-4acf-8bd2-51bd51b98920</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
