<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Akhir Pendaftaran_end_date</name>
   <tag></tag>
   <elementGuidId>878e88db-7c07-486c-ae63-e8a0cd1da754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='end_date']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#end_date</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88d11a57-24cf-4254-bb19-d853fdd614f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>1c0d314a-a0c6-4a02-99a4-41e807324c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6900a8b-efa6-4207-8f06-88523e2ca8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c06b7b31-ed2e-4da0-92b0-bb6fd2f24386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TTTT-BB-HH</value>
      <webElementGuid>cd11b950-d895-41bd-b51a-3e01aa851b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{4}-[0-9]{2}-[0-9]{2}</value>
      <webElementGuid>8efd98b5-271f-4d95-802d-a5a133c84c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>2b16cf42-d195-4b0b-8b43-af4175d1b2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0000-00-00</value>
      <webElementGuid>f0f88481-5dad-4fd0-9d11-c0aaac176e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_date&quot;)</value>
      <webElementGuid>0873757c-8881-43db-946a-e9d97ab46bf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='end_date']</value>
      <webElementGuid>e37f251a-49e3-4c17-ae20-afc7301a9a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[4]/input</value>
      <webElementGuid>4affe5cb-25d4-4b3a-91fe-5735f9c01616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>31a29158-7b1f-4d28-9ee0-715201947c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'end_date' and @type = 'text' and @placeholder = 'TTTT-BB-HH' and @id = 'end_date']</value>
      <webElementGuid>a25fa773-9938-4ab5-9cdc-b135819037b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
