<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Opsional)_brochure</name>
   <tag></tag>
   <elementGuidId>2cfa9af7-ad08-45bc-af97-be7edcea2c1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadBrochure']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploadBrochure</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>710b1a94-915e-40b7-83db-bcbf8041cc3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>brochure</value>
      <webElementGuid>0d00f14a-e170-45c7-acf9-9ea49e3fb943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>a5a4e0b6-a0b2-4d8e-b9b1-5229f8f61a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>850cdf9b-560c-4145-bd96-25f46befd400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadBrochure</value>
      <webElementGuid>d713c5c5-fe98-4c7f-a8b2-c62db3a5c364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadBrochure&quot;)</value>
      <webElementGuid>75a3d3ac-6865-469f-baf4-dd8f55dea480</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadBrochure']</value>
      <webElementGuid>72a6a9a3-5dcc-4eeb-a6dc-b8e7bb0f4241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>d28a19be-495e-4420-b364-e3ac3ff8bf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>c88160d9-64ff-4489-a5fd-3fa2ba0e8cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'brochure' and @type = 'file' and @id = 'uploadBrochure']</value>
      <webElementGuid>dda61a96-1243-49b9-a95b-4dc616dbcb90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
