<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Terima</name>
   <tag></tag>
   <elementGuidId>bc33a212-cf18-4566-80da-a8445a0035d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'acceptBtn' and @type = 'button' and (text() = 'Terima' or . = 'Terima')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='acceptBtn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#acceptBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ec0ed3bd-6fa5-4cc1-8d29-0a54a7b46f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptBtn</value>
      <webElementGuid>69877e2f-e5bb-4706-ad45-525cd6791700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>15f2a06b-403f-40d5-a66d-a9c3942df370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-success</value>
      <webElementGuid>29892024-78ea-4894-b89b-ec37235ec8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>92e73a03-fc26-4271-910b-89676cd02a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terima</value>
      <webElementGuid>df2e7e81-37be-4eeb-9d8c-a39ea34a577d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptBtn&quot;)</value>
      <webElementGuid>34d22c2d-ece0-4175-9014-de0ba2b970b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='acceptBtn']</value>
      <webElementGuid>8a3f9feb-1908-48ca-a66f-d4611f89767e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verifyCompanyModal']/div/div/div[3]/div/div/button</value>
      <webElementGuid>cd93ebe3-efe9-492a-a0a3-90c47c35c582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Jaya Abadi Selamanya'])[2]/following::button[1]</value>
      <webElementGuid>5898369a-6c94-4210-a4df-2f24dfb7151f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Perusahaan'])[3]/following::button[2]</value>
      <webElementGuid>e06c9c4c-c624-4be4-b383-74b32a6c9b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak'])[1]/preceding::button[1]</value>
      <webElementGuid>ef935356-2711-4fa7-a990-1d0dc6adaf9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2021 - GERATISIN'])[1]/preceding::button[2]</value>
      <webElementGuid>99506c33-cdc2-4469-ac21-c17575dcaa61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terima']/parent::*</value>
      <webElementGuid>b95e8799-2146-4cdf-a775-cd523b6557da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>42787ff5-558f-49ae-943d-d9f5dc52c8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'acceptBtn' and @type = 'button' and (text() = 'Terima' or . = 'Terima')]</value>
      <webElementGuid>59ee9576-ea15-42bb-a90c-491e16e12a5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
