<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Terima</name>
   <tag></tag>
   <elementGuidId>bc33a212-cf18-4566-80da-a8445a0035d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='acceptBtn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'acceptBtn' and @type = 'button' and (text() = 'Terima' or . = 'Terima')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c2c3716e-9cd8-41fd-aa7c-71368e5d656e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptBtn</value>
      <webElementGuid>5e493358-dc07-4c3b-99d7-fedcbea06e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e0d502ef-8bd8-44ff-a1bc-dd7726988e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-success</value>
      <webElementGuid>de199ca7-a4f2-4ccc-bdd6-079b4aed44dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5b62fe56-a9b2-4139-ba72-016c5d6fa9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terima</value>
      <webElementGuid>88de63ca-3a30-46f0-8382-373d0de44000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptBtn&quot;)</value>
      <webElementGuid>6f7772ea-1e91-4a6c-840b-325d789142fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='acceptBtn']</value>
      <webElementGuid>a83403b3-4c8d-4251-afbc-212534ee5bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verifyCompanyModal']/div/div/div[3]/div/div/button</value>
      <webElementGuid>9c58318b-605f-4c63-83ca-e94a419d709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Jaya Abadi Selamanya'])[2]/following::button[1]</value>
      <webElementGuid>a541438c-deb5-4934-9fd9-7e9f993f7202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Perusahaan'])[3]/following::button[2]</value>
      <webElementGuid>6edf0ac4-b602-4f26-a866-b13f6e70b728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tolak'])[1]/preceding::button[1]</value>
      <webElementGuid>26f85acb-1ed0-4eef-8cc9-87493b949561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2021 - GERATISIN'])[1]/preceding::button[2]</value>
      <webElementGuid>97ae0160-ef1e-450b-949e-44d7316162db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terima']/parent::*</value>
      <webElementGuid>08c5b4f5-baf8-4e34-a055-f2afdf9d8765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>c029b68a-746d-4481-9a9b-d01edf01cdb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'acceptBtn' and @type = 'button' and (text() = 'Terima' or . = 'Terima')]</value>
      <webElementGuid>fcf9e9da-e5cf-411e-9b60-e332529d6f9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
