<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload Brosur Baru_brochure</name>
   <tag></tag>
   <elementGuidId>6823af3c-9353-4fd3-9f9e-5f3e93abe781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadBrochure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadBrochure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af226907-43b2-4d82-a7aa-1c63d9eef261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>brochure</value>
      <webElementGuid>bec2241c-0b2f-4d40-b807-c7c88a9cf0c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1ec46b5a-2f4b-48b2-93ba-a33c0820d9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>8db86ba6-ad04-4b4e-aaae-1f70929aab4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadBrochure</value>
      <webElementGuid>c0335b88-e70f-4282-9672-dc2ddaaec8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadBrochure&quot;)</value>
      <webElementGuid>694e8857-9adc-4e39-977a-499aa49dffcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadBrochure']</value>
      <webElementGuid>d65b40e0-da13-44bd-be29-3d6cd5ca36a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>55c048d6-4220-4492-8213-d97433fcb006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>3c0d068d-0a8d-4829-a906-6dca922209f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'brochure' and @type = 'file' and @id = 'uploadBrochure']</value>
      <webElementGuid>64a0c18f-3a5e-4f6e-9ee2-c8f72448c6d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
