<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload Dokumen Verifikasi_document</name>
   <tag></tag>
   <elementGuidId>c1a0b6a3-c094-49b5-b3bb-7288352a8819</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadDoc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uploadDoc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51f76221-7670-4d21-a03d-e6cd8cbd5963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>document</value>
      <webElementGuid>751fbe5a-7f27-4b3e-ace1-a048a32015c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>b51bdec2-f3ad-4f56-8d27-37d604467440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>e1aa2e1f-7cb5-4ef3-ab1d-8cd0f752641f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadDoc</value>
      <webElementGuid>ca80678d-6a0a-4fe1-ae9e-de330a1295ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadDoc&quot;)</value>
      <webElementGuid>57dfefd9-2d7b-4ead-b6a0-016a15ddad6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadDoc']</value>
      <webElementGuid>3bb84a5f-e64f-45ec-ab92-29535fb95541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div/input</value>
      <webElementGuid>659a8bb1-4728-4817-9bee-3f655f282d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>8a9ef397-6b7f-4bb9-80fc-6601ead87975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'document' and @type = 'file' and @id = 'uploadDoc']</value>
      <webElementGuid>ed9b99a5-f47a-4470-8c58-3b9cb42da1fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
