<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat Detail</name>
   <tag></tag>
   <elementGuidId>c0e855db-1ffa-47be-a642-34ec3ff8bc02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Lihat Detail')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.small-box-footer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>816b896e-6166-4bac-bbe3-4cf9bf69808a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://108.136.150.164/admin/scholarship</value>
      <webElementGuid>6ef0f421-aa9b-4d86-93da-783479d2adda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small-box-footer</value>
      <webElementGuid>207a0bb0-07ca-4a1a-97c8-55453426c269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lihat Detail </value>
      <webElementGuid>ea630ffc-4b16-4581-9718-82789e6d01cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sidebar-mini layout-fixed&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-4 col-6&quot;]/div[@class=&quot;small-box bg-success&quot;]/a[@class=&quot;small-box-footer&quot;]</value>
      <webElementGuid>b742ec49-708d-4e6c-9939-9793df8c2e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat Detail')]</value>
      <webElementGuid>51eeb29d-4057-470b-bd70-7776f9fe8c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>b9c7adb7-d1d3-49fc-9059-60c3c8eb00e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GERATISIN'])[1]/following::a[10]</value>
      <webElementGuid>d6e69000-8622-42a2-826e-4cc43bb03f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[2]/preceding::a[1]</value>
      <webElementGuid>feba41a0-9d21-407a-8d5e-13e93026c341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Detail'])[3]/preceding::a[2]</value>
      <webElementGuid>8fd5f793-7662-47d3-8847-34e705921669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat Detail']/parent::*</value>
      <webElementGuid>6af98b50-d1d4-48f4-9cc3-0f5681a430f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://108.136.150.164/admin/scholarship'])[2]</value>
      <webElementGuid>157e40f1-0c5a-4fa7-b3a4-5a80b9595cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/a</value>
      <webElementGuid>2ff81022-6900-4e85-aca3-5d2ffa717450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://108.136.150.164/admin/scholarship' and (text() = 'Lihat Detail ' or . = 'Lihat Detail ')]</value>
      <webElementGuid>794d3079-90a0-496b-b633-951608345c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
