<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Upload Dokumen Verifikasi_document</name>
   <tag></tag>
   <elementGuidId>667e98e8-af3f-4504-962e-ac0b409fc1d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadDoc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadDoc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d20c0514-9010-41ce-8dc3-6c7114708713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>document</value>
      <webElementGuid>a28d48af-36d5-4b9d-b381-02e5f914b8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>8f80aa29-049e-435c-9e54-304e51a4243b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>73005142-17da-47f9-ae3a-82481ec45a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadDoc</value>
      <webElementGuid>6d1723df-f1c2-4018-a73f-0f46eefb739f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadDoc&quot;)</value>
      <webElementGuid>9df42632-5cea-4844-b0d5-2bd4d729e29d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadDoc']</value>
      <webElementGuid>2c22040d-6e29-45f3-a508-f69be9bb18d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div/input</value>
      <webElementGuid>b070e274-a95f-4e8f-9dda-3f27d4848eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>e75b36f0-44c5-47e9-a9a1-72f5a0e39c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'document' and @type = 'file' and @id = 'uploadDoc']</value>
      <webElementGuid>57fa03cc-96c6-4691-a79a-6ccf12ada0c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
