<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tolak</name>
   <tag></tag>
   <elementGuidId>035fa639-e721-4f3e-b397-458c3fc1c0e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#deniedBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='deniedBtn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'deniedBtn' and @type = 'button' and (text() = 'Tolak' or . = 'Tolak')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7baa4b78-31ae-4751-922a-5e1d4cd6d4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>deniedBtn</value>
      <webElementGuid>20151cc2-6d2d-4173-9d25-91a3a5e8cab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17d32061-2b2f-4344-bf64-552ef5fea23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 btn btn-danger</value>
      <webElementGuid>89d252ae-c714-41b9-ac94-725caf57a212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>b1b2e274-0bd4-4e9a-bf63-1cc747e93a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tolak</value>
      <webElementGuid>07af81af-c666-4541-a8d4-b8350eac3181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;deniedBtn&quot;)</value>
      <webElementGuid>a3c97e52-09df-4bf2-b2ad-69351e287972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='deniedBtn']</value>
      <webElementGuid>4c7adf7f-cc8f-4115-8ffd-c6a54badee4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='verifyCompanyModal']/div/div/div[3]/div/div[2]/button</value>
      <webElementGuid>b6a99530-ed0c-4c38-aee5-ec79a5c83c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terima'])[1]/following::button[1]</value>
      <webElementGuid>01a522a7-03b7-4acc-aadd-e340ad4cac88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Company'])[2]/following::button[2]</value>
      <webElementGuid>429ab392-3546-4b6b-99b9-ffd78b9e0d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2021 - GERATISIN'])[1]/preceding::button[1]</value>
      <webElementGuid>e2f02837-5990-4475-a7be-23f1d015ce39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'deniedBtn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>6b310861-fa49-463c-a4b0-06ad8459e2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tolak']/parent::*</value>
      <webElementGuid>01551532-d9b1-4c9c-8642-cba4e8a1bfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>cc747a03-1090-4397-a01a-c446241f1652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'deniedBtn' and @type = 'button' and (text() = 'Tolak' or . = 'Tolak')]</value>
      <webElementGuid>2519e55a-acf6-4462-8203-3cb4dc84777e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
