<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verifikasi</name>
   <tag></tag>
   <elementGuidId>336de08d-325a-46a7-b5b8-b5912f86b335</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='company-table']/tbody/tr/td[4]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = ' Verifikasi' or . = ' Verifikasi')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>beefc2e3-2257-45d5-8bcc-983b92281784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-info</value>
      <webElementGuid>fd3e5b4f-d09c-4cee-b7fd-6ae2fc171393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>2e8c8715-2397-4621-999d-dd7f0fb3a43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#verifyCompanyModal</value>
      <webElementGuid>0211bcd9-ae38-49ed-970a-5724d2449c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>27e0b505-6029-4ad9-86ce-ef1d47124229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>Test Company</value>
      <webElementGuid>3b174335-49e6-42ee-9e2e-cb5524934c04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Verifikasi</value>
      <webElementGuid>7b1d9828-da60-4ff9-9767-b41cc1ebfdfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;company-table&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[4]/button[@class=&quot;btn btn-info&quot;]</value>
      <webElementGuid>4375b7c0-ab73-498c-9bbc-d3457b727056</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='company-table']/tbody/tr/td[4]/button</value>
      <webElementGuid>4f8ff99e-7216-4ab4-bbfb-bdcd0c00fcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[1]/following::button[1]</value>
      <webElementGuid>04eb80ea-e8a9-4c61-961d-0e2eb38ccf94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='testcomp@email.com'])[1]/following::button[1]</value>
      <webElementGuid>2abb57c2-a6de-4dc6-9d22-f560765fafac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Aswin'])[1]/preceding::button[1]</value>
      <webElementGuid>c5178bb9-16eb-4db2-ade5-fca811534459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='company@vvpl.com'])[1]/preceding::button[1]</value>
      <webElementGuid>e87a7b1a-cab3-4645-aeac-04512d0dc880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verifikasi']/parent::*</value>
      <webElementGuid>11d05ee9-49b1-4314-87b8-9cda3ac2cb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4bce1fa4-1cc7-450a-a867-50eb1d976c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Verifikasi' or . = ' Verifikasi')]</value>
      <webElementGuid>a5e0badd-5325-4bbf-97b2-2ce500b0e876</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
