<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link Beasiswa_link</name>
   <tag></tag>
   <elementGuidId>a7e4ae50-fa4c-448c-83cd-a74b6fb05e15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e21a4b5-05c3-4cce-8bcb-4c26f9bdc55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>3c320482-7f09-45b8-9d4a-2f8ec8d25a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d4b59e1-0f31-4e85-811f-e46cc259e38f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a87a9b11-5754-434e-9602-f90f77efc939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>22484db3-5ec1-4298-950e-06d2ae14c1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link&quot;)</value>
      <webElementGuid>cad89221-f5da-4362-8ede-c5123abbdcbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='link']</value>
      <webElementGuid>bdfc5821-e94b-49db-8378-38c08f767d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[5]/input</value>
      <webElementGuid>db245897-cc71-4a6d-9eb7-8a36b1531e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6b2b72d8-da97-4123-ba40-d6378244fa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'link' and @type = 'text' and @id = 'link']</value>
      <webElementGuid>5b598d75-5d2a-4f25-8549-0289fe21206c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
