<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Opsional)_brochure</name>
   <tag></tag>
   <elementGuidId>e45eb338-5eb7-4250-86a7-2697508cd2ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadBrochure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadBrochure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a576045b-6812-47a6-b62f-fe84e065300b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>brochure</value>
      <webElementGuid>7dc9b0b1-87bf-4aaf-9490-9dcb888ee2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>ba6c12c7-120b-4ada-a601-e16c73d3a498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>a36f1711-803a-4cac-a7bb-f4be64a03ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadBrochure</value>
      <webElementGuid>9ddf68a6-84ea-4acb-9c1a-e20a3bad849b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadBrochure&quot;)</value>
      <webElementGuid>4782d197-0343-4c2e-9534-551c5d6a7473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadBrochure']</value>
      <webElementGuid>b1d7f414-83df-4e74-a491-b9c794689b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>05f8e2f4-45b4-45cb-94ff-b59f1bd93d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>69c4fe27-71f2-46ef-b155-572f22d9b56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'brochure' and @type = 'file' and @id = 'uploadBrochure']</value>
      <webElementGuid>760d667e-8539-4a08-99ab-4b735eac7423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
