<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Opsional)_brochure</name>
   <tag></tag>
   <elementGuidId>930c5a45-a4bf-4bfa-b963-e3381c207cfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploadBrochure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploadBrochure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c4597763-794f-4930-a91b-893f5b079e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>brochure</value>
      <webElementGuid>42f299d0-516f-4594-ad07-cca60be88ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>e982755b-c947-42b8-a70c-766190da197c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-file</value>
      <webElementGuid>08d980a0-8a24-4855-ad26-0494ef0fee56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploadBrochure</value>
      <webElementGuid>f5bac1f0-948b-422f-ba4c-dc20bb9df0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploadBrochure&quot;)</value>
      <webElementGuid>427b2ec2-11a8-463a-a3bc-5d43278d0a1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploadBrochure']</value>
      <webElementGuid>a023f4de-2c71-42da-bc40-b7552efd2775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[2]/input</value>
      <webElementGuid>b9365bc5-bc60-4224-ba88-5bc6cecfe748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>ed9966ae-1122-42d4-a099-1c479e050bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'brochure' and @type = 'file' and @id = 'uploadBrochure']</value>
      <webElementGuid>51b5e8fd-a762-4cbd-81a7-049c43c19f85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
