<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Akhir Pendaftaran_end_date</name>
   <tag></tag>
   <elementGuidId>ac49d03d-3307-4175-a5c4-fdeab3da59f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d442639c-292b-40e4-b045-c3ee559aeeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>c922e792-8268-4203-b86a-716c0a2ec32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0cae3cf8-08bc-468b-a314-774885a14c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bc251d18-9c6f-4bbd-abba-3599044db320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TTTT-BB-HH</value>
      <webElementGuid>29055e76-9246-405e-8f3e-0c52c1527b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{4}-[0-9]{2}-[0-9]{2}</value>
      <webElementGuid>92c92f05-8e99-412c-8c24-2782c2b01bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>804c1fa9-800f-422d-ae8c-f2c15111b75f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-05-12</value>
      <webElementGuid>f273606a-5e30-4293-b05d-384d36d2981c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_date&quot;)</value>
      <webElementGuid>ea56ae6f-a419-415b-88bb-a894b3390c70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='end_date']</value>
      <webElementGuid>ef8d36ed-e3a2-4b94-ab46-bd8a7496adc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[4]/input</value>
      <webElementGuid>a4345e9b-9a0e-45d8-a777-4b3d49141c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>fa91f867-ca3b-4443-befc-fe9c9d042157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'end_date' and @type = 'text' and @placeholder = 'TTTT-BB-HH' and @id = 'end_date']</value>
      <webElementGuid>a2af686f-e8b9-48ff-adbc-634eeecd1c29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
