<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link Beasiswa_link</name>
   <tag></tag>
   <elementGuidId>aff93417-2f65-4608-bf55-b9a0d5aa8f74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80a52149-f204-46f6-a8ef-676dcbb32a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>98121932-c101-40c4-92e6-0a448989c196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a0eedbc-1b4f-4efe-85d2-4986df4d9f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a41fc76-9850-4fba-8646-478423702fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>9d9fca16-3906-4fa3-ba5f-6dbef94badf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>www.beasiswa-anak-negri.com</value>
      <webElementGuid>66de0705-015c-4731-92c8-1d458a2ee181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link&quot;)</value>
      <webElementGuid>1b7b39cf-6c14-42c8-b23a-cb26b174de37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='link']</value>
      <webElementGuid>d8748d74-873a-40fd-8f2b-9f27d3d2a257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[5]/input</value>
      <webElementGuid>f1441c8d-80cb-471e-a030-ec67d644981f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>45f1e390-8891-4181-83ec-8ea19241ed81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'link' and @type = 'text' and @id = 'link']</value>
      <webElementGuid>3f48324c-e532-4166-a1d2-432f50bf7f94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
