<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Akhir Pendaftaran_end_date</name>
   <tag></tag>
   <elementGuidId>4bc11b39-bc77-4bdd-b83e-144edc072e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#end_date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='end_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd73ea18-d7a8-4d56-8d43-489c141b46be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>79c53d77-62fb-491e-8a13-bcacb6a77c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0bc7382c-067c-4a88-a1fb-8ba252ab12a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f0602f66-1005-4cd4-b529-7cf0faac0320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TTTT-BB-HH</value>
      <webElementGuid>f1d302db-9d32-4533-9bb7-dc04d28ecf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]{4}-[0-9]{2}-[0-9]{2}</value>
      <webElementGuid>45aaa637-93fb-42dc-a2a0-29b45ca6b8c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>end_date</value>
      <webElementGuid>a20bd705-82ba-4e57-9133-d9b9cbd6a7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2023-05-12</value>
      <webElementGuid>3ea572c4-a151-4b4b-a923-466229ae56ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;end_date&quot;)</value>
      <webElementGuid>871c4dce-0412-407e-b7c4-ee3bd93fc2a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='end_date']</value>
      <webElementGuid>07f1df11-6099-4718-85c7-0402a8bdad3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[4]/input</value>
      <webElementGuid>c35b693d-a89b-4dad-a502-021e9626644f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>0e5a9461-3a72-4214-b63f-99a9956be0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'end_date' and @type = 'text' and @placeholder = 'TTTT-BB-HH' and @id = 'end_date']</value>
      <webElementGuid>6d591748-da1a-4533-bc16-81e8bbcb0b26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
