<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Link Beasiswa_link</name>
   <tag></tag>
   <elementGuidId>dc94a634-e0ca-4fbb-9d40-5b0d764c3793</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='link']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>159e7fdc-9bec-43b3-bf49-6687d0e628af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>8795ea40-e215-455b-b42b-8bdcbf2d132e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33ff4856-59d7-461c-acb3-16403910b105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>24b6d054-8ef2-49a0-8c69-3ecc5ed522ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>46ef18d2-7bc4-47fa-8424-c88ac93ee390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>www.beasiswa-jaya-abadi.com</value>
      <webElementGuid>74186863-9d34-412a-9c79-e2e85b155a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link&quot;)</value>
      <webElementGuid>253dd4b5-8321-4269-b461-ac7b1b49b2f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='link']</value>
      <webElementGuid>d78b588c-d1ca-424a-b0cc-217c4cefca07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[2]/div/div/form/div[5]/input</value>
      <webElementGuid>dd8cd6f8-5740-41f6-af4d-7706274bca3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>b75314fc-106c-426b-9aa1-eb7cc0d568b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'link' and @type = 'text' and @id = 'link']</value>
      <webElementGuid>c0425e14-fa0d-4d2a-9fa0-ea2c153e2f2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
